-- Migration: Add factual_correctness_score and new_clause_flag to LCL
-- Date: 2025-11-03
-- Description: Adds two new fields required for the two-tier architecture (LCL + LCSTX)
--              - factual_correctness_score: Measures GPT's confidence in drafted clauses
--              - new_clause_flag: Marks AI-drafted clauses pending human verification

-- Add factual_correctness_score (0.000 to 1.000)
ALTER TABLE legal_clause_library
ADD COLUMN IF NOT EXISTS factual_correctness_score NUMERIC(4,3)
  CHECK (factual_correctness_score IS NULL OR (factual_correctness_score >= 0 AND factual_correctness_score <= 1))
  DEFAULT NULL;

COMMENT ON COLUMN legal_clause_library.factual_correctness_score IS
'Factual correctness score from 0.000 to 1.000 generated by GPT during New Clause Discovery.
Used to prioritize HITL review:
- NULL = not yet scored (manual entry or pre-existing clause)
- <0.85 = requires immediate verification (high priority)
- 0.85-0.90 = requires standard review (medium priority)
- ≥0.90 = auto-approved (low priority review)';

-- Add new_clause_flag (marks AI-drafted clauses)
ALTER TABLE legal_clause_library
ADD COLUMN IF NOT EXISTS new_clause_flag BOOLEAN DEFAULT false NOT NULL;

COMMENT ON COLUMN legal_clause_library.new_clause_flag IS
'Marks clauses created by AI via New Clause Discovery workflow.
- true = pending verification (not yet approved by admin)
- false = verified/approved (safe to use for reconciliation)

New clauses remain inactive (active=false) until admin approval.';

-- Index for HITL query performance
-- Finds new AI-drafted clauses that need review, ordered by factual correctness (worst first)
CREATE INDEX IF NOT EXISTS idx_lcl_factual_correctness
  ON legal_clause_library(factual_correctness_score NULLS LAST)
  WHERE new_clause_flag = true AND active = false;

COMMENT ON INDEX idx_lcl_factual_correctness IS
'Optimizes HITL review queue queries. Surfaces low-confidence AI-drafted clauses first.';

-- Index for unverified new clauses
CREATE INDEX IF NOT EXISTS idx_lcl_new_clause_flag
  ON legal_clause_library(created_at DESC)
  WHERE new_clause_flag = true AND active = false;

COMMENT ON INDEX idx_lcl_new_clause_flag IS
'Optimizes queries for pending new clause approvals (admin dashboard).';

-- Create view for admin review queue (new clauses only)
CREATE OR REPLACE VIEW v_new_clauses_pending_review AS
SELECT
  id,
  clause_id,
  clause_type,
  standard_text,
  category,
  risk_level,
  factual_correctness_score,
  created_at,
  CASE
    WHEN factual_correctness_score IS NULL THEN 'unscored'
    WHEN factual_correctness_score < 0.85 THEN 'high'
    WHEN factual_correctness_score < 0.90 THEN 'medium'
    ELSE 'low'
  END AS review_priority
FROM legal_clause_library
WHERE new_clause_flag = true
  AND active = false
ORDER BY
  CASE
    WHEN factual_correctness_score IS NULL THEN 0
    ELSE factual_correctness_score
  END ASC,
  created_at ASC;

COMMENT ON VIEW v_new_clauses_pending_review IS
'Admin dashboard view showing all AI-drafted clauses pending approval.
Ordered by priority (lowest factual correctness first).';
