-- Migration: Add embedding column to clause_boundaries for Phase 6
-- Date: 2025-11-13
-- Purpose: Enable vector similarity search for contract clauses

-- Add embedding column (1024 dimensions to match Cohere embed-english-v3.0)
ALTER TABLE clause_boundaries
ADD COLUMN embedding vector(1024);

-- Add index for efficient cosine similarity searches
-- IVFFlat index with 100 lists (good for ~10k-100k rows)
CREATE INDEX idx_clause_boundaries_embedding_cosine
  ON clause_boundaries
  USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);

-- Add comment for documentation
COMMENT ON COLUMN clause_boundaries.embedding IS 'Semantic embedding vector (1024-dim) generated by Cohere embed-english-v3.0 for similarity matching';
